#!/bin/sh

main() { parse_opts "$@"
	if [ -n "$governor" ]; then cpu_set_governor "$2"
	elif [ -n "$minfreq" ]; then cpu_set_minimum_frequency "$2"
	elif [ -n "$maxfreq" ]; then cpu_set_maximum_frequency "$2"
	else help ; exit 1; fi
}

cpu_set_governor() { for c in $(ls -d /sys/devices/system/cpu/cpu[0-9]*); do printf "$@" >$c/cpufreq/scaling_governor; done }
cpu_set_maximum_frequency() { for c in $(ls -d /sys/devices/system/cpu/cpu[0-9]*); do printf "$@" >$c/cpufreq/scaling_max_freq; done }
cpu_set_minimum_frequency() { for c in $(ls -d /sys/devices/system/cpu/cpu[0-9]*); do printf "$@" >$c/cpufreq/scaling_min_freq; done }

help() { printf 'Usage:\t%s' "$(basename $0) [option] [argument]

Options:
-g|--governor │ Set the CPU governor
-l|--minfreq  │ Set the CPU minimum frequency
-h|--maxfreq  │ Set the cPU maximum frequency
"; }

parse_opts() {
	while [ $# -gt 0 ]; do
		case "$1" in
			-h|--help) help ; exit 0 ;;
			-g|--governor) governor=1 ; shift ;;
			-l|--minfreq) minfreq=1 ; shift ;;
			-h|--maxfreq) maxfreq=1 ; shift ;;
			*) shift ;;
		esac
	done
}

main "$@"
